In [1]:
import pandas as pd

In [4]:
import_path = "../../../PLUTO/data.csv"

In [5]:
data_df = pd.read_csv(import_path)

In [6]:
data_df.head()

   zipcode  landuse  bldgarea  numfloors  yearbuilt
0  10019.0      5.0   57805.0        3.0     1920.0
1  10019.0      7.0  105562.0        0.0     2002.0
2  10023.0      3.0  225552.0       24.0     1968.0
3  10019.0      6.0   36184.0        4.0     1946.0
4  11219.0      2.0    3600.0        2.0     1930.0

In [7]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 859465 entries, 0 to 859464
Data columns (total 5 columns):
zipcode      838521 non-null float64
landuse      856535 non-null float64
bldgarea     858968 non-null float64
numfloors    857908 non-null float64
yearbuilt    858986 non-null float64
dtypes: float64(5)
memory usage: 32.8 MB

In [8]:
data_df.dropna(inplace=True)

In [9]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 835904 entries, 0 to 859464
Data columns (total 5 columns):
zipcode      835904 non-null float64
landuse      835904 non-null float64
bldgarea     835904 non-null float64
numfloors    835904 non-null float64
yearbuilt    835904 non-null float64
dtypes: float64(5)
memory usage: 38.3 MB

In [13]:
data_df.reset_index(inplace=True, drop=True)

In [14]:
data_df

        zipcode  landuse  bldgarea  numfloors  yearbuilt
0       10019.0      5.0   57805.0        3.0     1920.0
1       10019.0      7.0  105562.0        0.0     2002.0
2       10023.0      3.0  225552.0       24.0     1968.0
3       10019.0      6.0   36184.0        4.0     1946.0
4       11219.0      2.0    3600.0        2.0     1930.0
5       10019.0     11.0       0.0        0.0        0.0
6       10023.0      2.0    8063.0        4.0     1910.0
7       10023.0      3.0  490265.0       28.0     1930.0
8       10024.0      3.0   26910.0        6.0     1921.0
9       10024.0      3.0  162676.0       16.0     1928.0
10      10023.0      8.0    7800.0        1.0     1961.0
11      10023.0      4.0    2718.0        3.0     1900.0
12      10024.0      2.0    6550.0        4.0     1900.0
13      10024.0      2.0    5705.0        4.0     1900.0
14      11234.0      1.0     924.0        2.0     1925.0
15      10024.0      2.0    5760.0        4.0     1910.0
16      10024.0      3.0   10934.0        5.0     1910.0
17      10024.0      4.0   22874.0        5.0     1900.0
18      10024.0      2.0    5675.0        4.0     1930.0
19      10024.0      2.0    8440.0        4.0     1920.0
20      10024.0      1.0    4720.0        4.0     1910.0
21      10023.0      4.0  219794.0       27.0     1977.0
22      10023.0      1.0    5542.0        3.0     1899.0
23      10023.0      8.0    6380.0        4.0     1900.0
24      10023.0      2.0    4548.0        4.0     1920.0
25      10023.0      3.0   21328.0        8.0     1925.0
26      10023.0      5.0   31332.0        5.0     1925.0
27      11222.0      2.0    5000.0        4.0     1928.0
28      10024.0      5.0    8820.0        4.0     1920.0
29      10023.0      5.0   99663.0       12.0     1927.0
...         ...      ...       ...        ...        ...
835874  10019.0      3.0  100000.0        6.0     1942.0
835875  10019.0      5.0    3053.0        1.0     1930.0
835876  10036.0      3.0   65615.0        5.0     1926.0
835877  10036.0      2.0   11455.0        5.0     1925.0
835878  10036.0      4.0   17225.0        6.0     1930.0
835879  10019.0      2.0    8670.0        5.0     1901.0
835880  10036.0      3.0   60000.0        6.0     1900.0
835881  10036.0      3.0   29308.0        6.0     1910.0
835882  10036.0      8.0    8898.0        3.0     1910.0
835883  10036.0      2.0    6135.0        5.0     1930.0
835884  10019.0      5.0   45775.0        6.0     1910.0
835885  10019.0      3.0   21000.0        7.0     1910.0
835886  10019.0      8.0   75875.0        4.0     1959.0
835887  10308.0      1.0    1500.0        2.0     1925.0
835888  10019.0      5.0  263438.0       12.0     1915.0
835889  10019.0      3.0   31468.0        6.0     1911.0
835890  10019.0      4.0    4800.0        3.0     1910.0
835891  10019.0      3.0  104966.0       10.0     1957.0
835892  11436.0      1.0    1248.0        2.0     1930.0
835893  10036.0      5.0  122050.0        7.0     1962.0
835894  10465.0      1.0    2372.0        2.0     1930.0
835895  10036.0      8.0  203770.0        6.0     1940.0
835896  10036.0      4.0   19016.0        4.0     1900.0
835897  10036.0      2.0   15500.0        5.0     1910.0
835898  11378.0      6.0    6750.0        1.0     1931.0
835899  10019.0      4.0  195973.0       12.0     2000.0
835900  10019.0      5.0   45200.0        6.0     1940.0
835901  10019.0      7.0   11380.0        3.0     1927.0
835902  10019.0      5.0  490080.0        3.0     1937.0
835903  10036.0      6.0  211175.0        6.0     1950.0

[835904 rows x 5 columns]

In [15]:
data_df.to_csv("data.csv")